
Get http://localhost:3003/ping
###

Get http://localhost:3003/videos
###

Post http://localhost:3003/videos
Content-Type: application/json 

{
    "id": "v002",
    "titulo": "Exercicio POO II",
    "duracao": 160 
}
###

Put http://localhost:3003/videos/v001
Content-Type: application/json 

{
    "newTitulo": "Exercicio POO I",
    "newDuracao": 160 
}
###

Delete http://localhost:3003/videos/v001
###